# Generated by Django 5.0 on 2024-08-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='more2',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='support',
            name='more3',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='support',
            name='title2',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='support',
            name='title3',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
